services:
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
      - URL=app.rher92.com
    build: ./
    command: >
      bash -c "./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000 --settings=apolo.config.production"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
